"use client";

import ApprovalPanel from "../../components/ApprovalPanel";
import type { RerouteProposal } from "../../lib/types";

const mockProposals: RerouteProposal[] = [
  {
    id: "prop-1",
    flightId: "AA123",
    callsign: "AA123",
    currentRoute: "KLAX DCT PGS J146 TBC J18 HBU J60 LBF J94 OBH J10 DBQ J60 JOT KJFK",
    proposedRoute:
      "KLAX DCT PGS J146 TBC J18 HBU J60 LBF J94 OBH J10 PMM J60 JOT KJFK",
    riskBefore: 0.72,
    riskAfter: 0.34,
    reason:
      "Avoids convective activity in central corridor and reduces sector density.",
    createdAt: new Date().toISOString()
  }
];

export default function ApprovalsPage() {
  return (
    <div className="space-y-6">
      <h1 className="text-2xl font-semibold tracking-tight">
        Agent Reroute Approvals
      </h1>
      <p className="text-slate-300 text-sm max-w-2xl">
        Review proposed reroutes generated by the decision engine. Approving a
        reroute will apply the updated flight plan to the mission state.
      </p>

      <ApprovalPanel proposals={mockProposals} />
    </div>
  );
}
